[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/pix/create"
  to = "/.netlify/functions/pix-create"
  status = 200

[[redirects]]
  from = "/api/pix/status/*"
  to = "/.netlify/functions/pix-status?id=:splat"
  status = 200

[[redirects]]
  from = "/api/payevo/webhook"
  to = "/.netlify/functions/payevo-webhook"
  status = 200


[[redirects]]
from = "/_next/image"
to = "/.netlify/functions/next-image"
status = 200
force = true
